name: Erlang CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp:
          - "24.2.1.0"
          - "23.3.4.11"
          - "22.3.4.24"

    container:
      image: erlang:${{ matrix.otp }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref and dialyzer
        run: ./rebar3 do xref, dialyzer
      - name: Run eunit
        run: ./rebar3 eunit
